---
- import_role:
    name: install_zabbix_agent

- name: copy ceph.conf
  copy:
    src: ceph.conf
    dest: /etc/zabbix/zabbix_agent2.d/ceph.conf
    mode: '0644'
  register: result_configure

- name: restart zabbix agent
  service:
    name: zabbix-agent2
    state: restarted
  when: result_configure is change